
---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5


suites:
  - name: standalone_node
    run_list:
      - recipe[locustio::default]
    attributes:
      locustio:
        base_url: example.com
        uri_list:
          - {'uri': '/', 'weight': '20', 'identifier': 'home'}
        node_type: 'standalone'
        custom_test_file: 'custom_test.py'

  - name: master_node
    run_list:
      - recipe[locustio::default]
    attributes:
      locustio:
        base_url: example.com
        uri_list:
          - {'uri': '/', 'weight': '20', 'identifier': 'home'}
        node_type: 'master'
        custom_test_file: 'custom_test.py'



